In [29]:
from observatorio_laboral.offer.offer_controller import OfferController
from observatorio_laboral.offer.date_range import DateRange

text_fields = []
oc = OfferController(text_fields, keyspace="l4", table="l4_offers")
date_range = DateRange(1, 2016, 7, 2017)
source = "symplicity"

oc.load_offers(source, date_range)
print("Nro de conv. en la fecha ingresada: ", len(oc.offers))

oc.filter_offers_by_career("ECONOMÍA")
print("Nro de conv. de la carrera: ", len(oc.offers))

Nro de conv. en la fecha ingresada:  1801
Nro de conv. de la carrera:  1801


In [30]:
from observatorio_laboral.keywords_classifier.keywords_classifier import KeywordClassifier

features = []
for offer in oc.offers:
    features.append(offer.features)    

kwc = KeywordClassifier("proc_symplicity.txt")
kwc.read_configuration()
kwc.load_keywords()

results = kwc.run(features)

In [31]:
filtered_offers = []
filtered_results = []
for offer, result in zip(oc.offers, results):
    if 'practicante' not in result['positions']:
        filtered_offers.append(offer)
        filtered_results.append(result)
        
oc.offers = filtered_offers
results = filtered_results
len(filtered_offers)
    

1304

In [32]:
l4_count = {}
for result in results:
    for field in result:
        if field not in l4_count:
            l4_count[field] = {}
            
        for label in result[field]:        
            if label not in l4_count[field]:
                l4_count[field][label] = 0
            
            l4_count[field][label] += 1
        
import csv
for field in l4_count:
    with open("Resultados/Economia/" + field + ".csv", 'w') as csvfile:
        fieldnames = [field, 'nro_conv']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for label, count in l4_count[field].items():
            writer.writerow({field : label, 'nro_conv' : count})

In [33]:
for offer, result in zip(oc.offers, results):
    if 'Otros/no-menciona' in result['degrees']:
        print(offer.features)


{'Additional languages': '', 'Approved': 'Sí', 'Beneficios e información adicional': '- Cobertura EPS.\r\n- Planilla.\r\n- Utilidades.\r\n- Línea de Carrera.', 'Degree Level': '', 'Description': 'Asegurar la racionalidad, unidad y eficiencia de los procesos administrativos y financieros para cubrir las necesidades de la organización.\r\n\r\nFUNCIONES:\r\n\r\n• Elaborar y hacer seguimiento del presupuesto anual.\r\n• Dirigir los recursos financieros de ejecución del gasto asignados a la organización.\r\n• Efectuar el control previo y concurrente de las operaciones administrativas y financieras de la organización.\r\n• Emitir los informes respecto a la Ejecución Presupuestaria de Ingresos y Gastos.\r\n• Elaborar los informes Técnico - Financieros de las actividades de la organización.\r\n• Preparar los ratios financieros de la organización.\r\n• Garantizar y efectuar el seguimiento de las medidas correctivas y las recomendaciones contenidas en los informes de control.', 'Employer': 'SIST

In [47]:
oc.text_fields=['Job Title', 'Description', 'Qualifications']

In [48]:
offer_texts = oc.get_text()
punctuations = ['•','/', ')', '-']
translator = str.maketrans("".join(punctuations),' '*len(punctuations))

proc_data = []
for text in offer_texts:
    text = text.lower()
    text = text.translate(translator)
    proc_data.append(text)
    
offer_texts = proc_data

X = offer_texts

In [72]:
# Clasificacion
import pickle

with open("Pickle/pipelineEconomia.p", "rb") as file:
    pipeline = pickle.load(file)
    y = pipeline.predict(X)



In [73]:
with open("Pickle/binarizerEconomia.p", "rb") as file:
    mlb = pickle.load(file)
    labels = mlb.inverse_transform(y)

In [78]:
cnt = 0
for offer, label in zip(oc.offers, labels):
    if not label:
        print(offer.id)
        print(offer.features['Organization Name'])
        print()
        
cnt    

analista de inversiones elaboración de reportes sectoriales y de mercado apoyo en la elaboración del análisis de inversiones de renta variable o fija análisis de crédito valorización de empresas elaboración del reporte semanal de resultados corporativos trimestrales y otros relacionados monitorear las empresas en cartera y brindar alertas oportunas ante cambios en las condiciones de mercado 1 a 2 años de experiencia incluido prácticas pre profesionales
Rimac Internacional Compañía de Seguros y Reaseguros (20100041953)

analista de modelos analíticos analizar construir dar seguimiento y control en la administración de modelos estadísticos de riesgo realizar análisis ad hoc para la identificación de los factores de riesgo propios de la cartera
CENCOSUD Perú S.A (20517905454)

analista de relaciones con inversionistas 1 procesar y analizar el reporte de políticas operaciones y desempeño de la gestión de activos y pasivos a ser publicado en el portal de relaciones con inversionistas en cas

0

In [71]:
mlb.classes_

array(['EM', 'FI', 'MC', 'PP'], dtype=object)

In [54]:
labels

[('FI', 'PP'),
 ('FI',),
 ('FI', 'PP'),
 ('FI', 'PP'),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('FI',),
 ('FI',),
 ('FI', 'PP'),
 ('PP',),
 ('PP',),
 ('FI',),
 ('FI',),
 (),
 ('PP',),
 ('PP',),
 ('PP',),
 (),
 ('FI', 'PP'),
 ('FI',),
 ('FI',),
 ('PP',),
 ('FI',),
 ('FI', 'PP'),
 ('FI',),
 ('FI', 'PP'),
 ('FI', 'PP'),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('FI', 'PP'),
 (),
 ('PP',),
 ('FI',),
 ('FI',),
 ('FI',),
 ('FI',),
 ('FI', 'PP'),
 ('FI', 'PP'),
 (),
 ('MC',),
 (),
 ('FI', 'PP'),
 ('FI',),
 ('FI',),
 ('PP',),
 (),
 ('FI',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('FI', 'PP'),
 ('FI', 'PP'),
 ('PP',),
 ('FI', 'PP'),
 ('FI', 'PP'),
 (),
 ('PP',),
 (),
 ('FI', 'PP'),
 ('FI', 'PP'),
 ('PP',),
 (),
 ('FI', 'PP'),
 ('PP',),
 ('FI', 'PP'),
 (),
 ('FI', 'PP'),
 ('FI',),
 ('FI', 'MC'),
 ('PP',),
 ('FI', 'MC'),
 ('FI', 'PP'),
 ('FI', 'PP'),
 (),
 ('FI',),
 ('FI',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('PP',),
 ('FI', 'PP'),
 ('PP',),
 ('PP',),
 (),
 ('PP',),
 ('PP',),


In [43]:
pipeline

Pipeline(memory=None,
     steps=[('vec', TfidfVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.5, max_features=None, min_df=1,
        ngram_range=(1, 3), norm='l2', preprocessor=None, smooth_idf=True,
    ...lti_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
          n_jobs=1))])

In [45]:
for k in y:
    print(k)

[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]


In [1]:
from observatorio_laboral.offer.offer_controller import OfferController
from observatorio_laboral.offer.date_range import DateRange

text_fields = []
oc = OfferController(text_fields = ["Job Title", "Description", "Qualifications"])
date_range = DateRange(1, 2013, 5, 2017)
source = "symplicity"

# Get offers by date range
oc.load_offers(source, date_range)
print("Nro de conv. en la fecha ingresada: ", len(oc.offers))

# Get offers by career
oc.filter_offers_by_career("ECONOMÍA")
print("Nro de conv. de la carrera: ", len(oc.offers))

Nro de conv. en la fecha ingresada:  80706
Nro de conv. de la carrera:  12653


In [ ]:
from observatorio_laboral.keywords_classifier.keywords_classifier import KeywordClassifier


features = []
for offer in oc.offers:
    features.append(offer.features)    

kwc = KeywordClassifier("proc_symplicity.txt")
kwc.read_configuration()
kwc.load_keywords()
results = kwc.run(features)

In [10]:
from observatorio_laboral.offer.offer_controller import OfferController
from observatorio_laboral.offer.date_range import DateRange

oc = OfferController(text_fields = ["Job Title", "Description", "Qualifications"], keyspace="l4", table="l4_offers")
date_range = DateRange(1, 2013, 5, 2017)
source = "symplicity"
# Get offers by date range
oc.load_offers(source, date_range)
print("Nro de conv. en la fecha ingresada: ", len(oc.offers))

# Get offers by career
oc.filter_offers_by_career("ECONOMÍA")
print("Nro de conv. de la carrera: ", len(oc.offers))


# Get labeled offers
oc.filter_offers_by_field("Areas")
print("Nro de conv. clasificadas: ", len(oc.offers))

Nro de conv. en la fecha ingresada:  80706
Nro de conv. de la carrera:  12653
Nro de conv. clasificadas:  553


In [16]:
from observatorio_laboral.offer.offer import Offer
oc_train = OfferController(text_fields = ["Job Title", "Description", "Qualifications"], keyspace="l4", table="train_offers")
for offer in oc.offers:
    offer_train = Offer(offer.source, offer.year, offer.month, offer.id, offer.features, offer.careers)
    offer_train.Insert()    


In [4]:
l4_count = {}
for result in results:
    for field in result:
        if field not in l4_count:
            l4_count[field] = {}
            
        for label in result[field]:        
            if label not in l4_count[field]:
                l4_count[field][label] = 0
            
            l4_count[field][label] += 1
        
l4_count

{'degrees': {'1 universidad incompleta': 3266,
  '2 universidad completa': 16,
  '3 bachiller': 4966,
  '4 titulado': 2956,
  '5 diplomado': 18,
  '7 maestría': 113,
  '8 doctorado': 7},
 'languages': {'alemán': 4,
  'francés': 12,
  'inglés': 7981,
  'italiano': 5,
  'portugués': 21},
 'positions': {'analista': 3423,
  'asistente': 1396,
  'consultor': 441,
  'dirección': 456,
  'docente': 54,
  'ejecutivo': 1040,
  'gerencia media': 766,
  'operativo': 36,
  'otros': 557,
  'practicante': 2915,
  'profesional especializado': 806,
  'supervisor': 657},
 'software': {'bases de datos': 1735,
  'bloomberg': 140,
  'cad': 1147,
  'data warehousing': 1039,
  'erp': 1345,
  'eviews': 99,
  'excel': 9963,
  'matlab': 34,
  'ofimática': 10341,
  'php': 28,
  'pls': 3,
  'power point': 2551,
  'programación': 1769,
  'project': 231,
  'ruby': 1,
  'sas': 72,
  'seguridad informática': 62,
  'software de gestión': 259,
  'software estadístico': 316,
  'software financiero': 178,
  'software mat

In [5]:
import csv
for field in l4_count:
    with open(field + ".cvs", 'w') as csvfile:
        fieldnames = [field, 'nro_conv']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for label, count in l4_count[field].items():
            writer.writerow({field : label, 'nro_conv' : count})
        
    
    

    

In [23]:
from observatorio_laboral.offer.offer import Offer
from cassandra.cluster import Cluster

Offer.ConnectToDatabase(keyspace="l4", table="l4_offers")

select_cmd = """
            SELECT * FROM symplicity.new_offers;
             """
cluster = Cluster()
session = cluster.connect()
result = session.execute(select_cmd);

for row in result:
    id = row.id
    year = row.year
    month = row.month
    careers = row.careers
    features = row.features
    source = "symplicity"
    
    if careers and "INGENIERÍA MECATRÓNICA" in careers:
        offer = Offer(source, year, month, id, features, careers)
        offer.Insert()

    #if (id, year, month, source) in ids:
    #    offer = Offer(source, year, month, id, features, careers)
        #offer.Insert()

In [24]:
from observatorio_laboral.offer.offer_controller import OfferController
from observatorio_laboral.offer.date_range import DateRange

oc = OfferController(text_fields=[], keyspace="l4", table="l4_offers")
date_range = DateRange(7, 2016, 6, 2017)
source="symplicity"

oc.load_offers(source, date_range)
career = "INGENIERÍA MECATRÓNICA"

oc.filter_offers_by_career(career)






In [25]:
len(oc.offers)

1564

In [26]:
import csv

with open("Data_A_Limpiar/Mecatrónica.csv", "w") as csvfile:    
    fieldnames = ["id", "year", "month", "Job Title", "Description", "Qualifications", "Organization Name", "Majors/Concentrations"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for offer in oc.offers:
        writer.writerow({
            'id' : offer.id,
            'year' : offer.year,
            'month' : offer.month,
            'Job Title' : offer.features['Job Title'],
            'Description' : offer.features['Description'],
            'Qualifications' : offer.features['Qualifications'],
            'Organization Name' : offer.features['Organization Name'],
            'Majors/Concentrations' : offer.features['Majors/Concentrations'],            
        })
    

In [81]:
#Pasar ofertas limpiadas a tabla de l4_offers

import csv
ids = []
with open("Data A Clasificar/mecatronica.csv") as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        id = row["id"]
        year = int(row['year'])
        month = int(row['month'])
        source = "symplicity"
        mark = row['Aceptado']
        if mark == 'a':
            ids.append((id,year,month, source))
            
from cassandra.cluster import Cluster
from observatorio_laboral.offer.offer import Offer
from observatorio_laboral.offer.offer_controller import OfferController
from observatorio_laboral.offer.date_range import DateRange

Offer.ConnectToDatabase("l4", "l4_offers")
cluster = Cluster()
session = cluster.connect()

select_cmd = """
            SELECT * FROM symplicity.new_offers;
             """
result = session.execute(select_cmd);

for row in result:    
    id = row.id
    year = row.year
    month = row.month
    careers = row.careers
    features = row.features
    source = "symplicity"

    if (id, year, month, source) in ids:
        offer = Offer(source, year, month, id, features, careers)
        offer.Insert()